# Generated by Django 3.2.8 on 2022-01-18 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.IntegerField()),
                ('userEmail', models.EmailField(max_length=254)),
                ('userName', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletBal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('walletTransaction', models.BooleanField(default=False)),
                ('transactionAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transactionTimeStamp', models.DateTimeField(auto_now_add=True)),
                ('transactionDescription', models.CharField(max_length=100)),
                ('transactionType', models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2)),
                ('transactionCategory', models.CharField(choices=[('FOOD', 'Food'), ('ENTERTAINMENT', 'Entertainment'), ('SHOPPING', 'Shopping'), ('OTHER', 'Other')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapp.user')),
            ],
        ),
    ]
