# Generated by Django 3.2.8 on 2022-01-18 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0002_auto_20220118_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFraudAdvisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxAmount', models.IntegerField(default=10000)),
                ('maxNumberOfTransactionsInADay', models.IntegerField(default=5)),
                ('lastTransactionTS', models.DateTimeField(auto_now_add=True)),
                ('lastTransactionAmount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapp.user')),
            ],
        ),
    ]
