# Generated by Django 3.2.8 on 2022-01-18 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0003_userfraudadvisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userLocation',
            field=models.CharField(default='Mumbai', max_length=100),
        ),
    ]
