# Generated by Django 3.2.8 on 2022-01-19 16:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0004_user_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 16, 21, 27, 395829)),
        ),
        migrations.AlterField(
            model_name='userfraudadvisor',
            name='lastTransactionTS',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 16, 21, 27, 396829)),
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('reminderID', models.AutoField(primary_key=True, serialize=False)),
                ('reminderTitle', models.CharField(max_length=100)),
                ('reminderAmount', models.IntegerField(default=0)),
                ('reminderTimeStamp', models.DateTimeField(default=datetime.datetime(2022, 1, 19, 16, 21, 27, 396829))),
                ('reminderDescription', models.CharField(max_length=100)),
                ('reminderType', models.CharField(choices=[('AutoPay', 'AutoPay'), ('Reminder', 'Reminder')], max_length=10)),
                ('reminderCategory', models.CharField(max_length=100)),
                ('sendToUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sendToUser', to='cashapp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashapp.user')),
            ],
        ),
    ]
