# Generated by Django 3.2.8 on 2022-01-19 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0005_auto_20220119_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receiverPhoneNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='reminderTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 27, 54, 914622)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 27, 54, 913623)),
        ),
        migrations.AlterField(
            model_name='userfraudadvisor',
            name='lastTransactionTS',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 17, 27, 54, 914622)),
        ),
    ]
