# Generated by Django 3.2.8 on 2022-01-19 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0006_auto_20220119_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminderTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 23, 33, 18, 383645)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 19, 23, 33, 18, 382644)),
        ),
        migrations.AlterField(
            model_name='userfraudadvisor',
            name='lastTransactionTS',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 19, 23, 33, 18, 383645)),
        ),
    ]
