# Generated by Django 3.2.8 on 2022-01-20 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashapp', '0007_auto_20220119_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminderTimeStamp',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 3, 20, 14, 670092)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTimeStamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 20, 3, 20, 14, 669093)),
        ),
        migrations.AlterField(
            model_name='userfraudadvisor',
            name='lastTransactionTS',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 20, 3, 20, 14, 670092)),
        ),
    ]
